### ISSUE TITLE
hawaii-shell doesn't find headers unless I symlink them to /opt/include

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#166]
In order to get hawaii-shell to find the headers, I have to run
ln -s $INSTALLDIR/include/GreenIsland/greenisland $INSTALLDIR/include/greenisland
Thanks.

**Comment by n3rdopolis** [comment]
Hi. I just realized that these lines get logged out too, hopefuly they are helpful
hawaii-shell: 
hawaii-shell: -- Configuring done
hawaii-shell: CMake Error in compositor/CMakeLists.txt:
hawaii-shell:   Imported target "GreenIsland::GreenIsland" includes non-existent path
hawaii-shell: 
hawaii-shell:     "/include/GreenIsland"
hawaii-shell: 
hawaii-shell:   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
hawaii-shell: 
hawaii-shell:   * The path was deleted, renamed, or moved to another location.
hawaii-shell: 
hawaii-shell:   * An install or uninstall procedure did not complete successfully.
hawaii-shell: 
hawaii-shell:   * The installation package was faulty and references files it does not
hawaii-shell:   provide.

**Comment by plfiorini** [comment]
How do you build greenisland (I mean the cmake args)?

**Comment by n3rdopolis** [comment]
Hi. Sorry about the delay: I use
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_PREFIX_PATH=$INSTALLDIR -DLIB_INSTALL_DIR=$INSTALLDIR/lib/$(dpkg-architecture -qDEB_HOST_MULTIARCH)

**Comment by plfiorini** [comment]
Does this still happen?

**Comment by plfiorini** [comment]
Closing, feel free to reopen if it happens again.
