### ISSUE TITLE
hawaii crashed (core dump)

### ISSUE THREAD

**Issue by fleixi** [hawaii-desktop/hawaii-shell#178]
if i try to start hawaii i get this:

-----------------------------------------------------------------------------------------

[root@localhost hawaii-shell]# /usr/local/bin/hawaii
QML debugging is enabled. Only use this in a safe environment.
EGLFS: Screen Info
 - Physical size: QSizeF(0, 0)
 - Screen size: QSize(1920, 1080)
 - Screen depth: 32
== hwcomposer module ==
 * Address: 0xb2d77004
 * Module API Version: 1
 * HAL API Version: 100
 * Identifier: hwcomposer
 * Name: Samsung exynos5 hwcomposer module
 * Author: Samsung LSI
== hwcomposer module ==
== hwcomposer device ==
 * Version: 1010001 (interpreted as 1010001)
 * Module: 0xb2d77004
== hwcomposer device ==
QEglScreen 0x2ba20

Compositor ready, notify systemd on ""
kscreen: Launcher finished with exit code 2 , status 0
kscreen: Launcher failed to load any backend: KScreen will be useless
Screen configuration has an error: Failed to prepare backend
Aborted (core dumped)

-------------------------------------------------------------------------------------------------------

System is odroid-xu (armv7 with libhybris for hwcomposer)

Because of the small output i have added the output of strace:

http://pastebin.com/wtqjzBWa

and hawaii is linked to this:

[root@localhost hawaii-shell]# ldd /usr/local/bin/hawaii
        libQt5Core.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Core.so.5 (0xb6adb000)
        libQt5Gui.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Gui.so.5 (0xb6660000)
        libGreenIsland.so.0 => /usr/local/lib/libGreenIsland.so.0 (0xb660e000)
        libQt5Widgets.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Widgets.so.5 (0xb60c1000)
        libQt5Quick.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Quick.so.5 (0xb5dbc000)
        libQt5Qml.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Qml.so.5 (0xb5a2d000)
        libQt5Network.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Network.so.5 (0xb58f4000)
        libQt5Compositor.so.5 => /usr/local/Qt-5.5.0/lib/libQt5Compositor.so.5 (0xb5869000)
        libKF5Screen.so.6 => /usr/local/lib/libKF5Screen.so.6 (0xb5830000)
        libQt5DBus.so.5 => /usr/local/Qt-5.5.0/lib/libQt5DBus.so.5 (0xb57c1000)
        libwayland-client.so.0 => /usr/local/lib/libwayland-client.so.0 (0xb57b1000)
        libwayland-server.so.0 => /usr/local/lib/libwayland-server.so.0 (0xb579e000)
        libEGL.so.1 => /usr/local/lib/libEGL.so.1 (0xb5790000)
        libGLESv2.so.2 => /usr/local/lib/libGLESv2.so.2 (0xb5783000)
        libsystemd.so.0 => /lib/libsystemd.so.0 (0xb5742000)
        libstdc++.so.6 => /lib/libstdc++.so.6 (0xb566a000)
        libm.so.6 => /lib/libm.so.6 (0xb55f3000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xb55ce000)
        libc.so.6 => /lib/libc.so.6 (0xb5481000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xb5461000)
        libz.so.1 => /lib/libz.so.1 (0xb5445000)
        libicui18n.so.52 => /lib/libicui18n.so.52 (0xb528c000)
        libicuuc.so.52 => /lib/libicuuc.so.52 (0xb514c000)
        libicudata.so.52 => /lib/libicudata.so.52 (0xb3ad7000)
        libpcre16.so.0 => /lib/libpcre16.so.0 (0xb3a76000)
        libdl.so.2 => /lib/libdl.so.2 (0xb3a68000)
        libgthread-2.0.so.0 => /lib/libgthread-2.0.so.0 (0xb3a5e000)
        libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0xb393a000)
        librt.so.1 => /lib/librt.so.1 (0xb392b000)
        /lib/ld-linux-armhf.so.3 (0xb6f1a000)
        libpng16.so.16 => /lib/libpng16.so.16 (0xb38f8000)
        libxkbcommon.so.0 => /lib/libxkbcommon.so.0 (0xb38b6000)
        libQt5X11Extras.so.5 => /usr/local/Qt-5.5.0/lib/libQt5X11Extras.so.5 (0xb38b3000)
        libffi.so.6 => /usr/local/lib/libffi.so.6 (0xb38a3000)
        libhardware.so.2 => /usr/local/lib/libhardware.so.2 (0xb389a000)
        libhybris-common.so.1 => /usr/local/lib/libhybris-common.so.1 (0xb386c000)
        libandroid-properties.so.1 => /usr/local/lib/libandroid-properties.so.1 (0xb3860000)
        liblzma.so.5 => /lib/liblzma.so.5 (0xb3837000)
        libgcrypt.so.20 => /lib/libgcrypt.so.20 (0xb3793000)
        libgpg-error.so.0 => /lib/libgpg-error.so.0 (0xb3786000)
        libresolv.so.2 => /lib/libresolv.so.2 (0xb3765000)
        libdw.so.1 => /lib/libdw.so.1 (0xb371b000)
        libelf.so.1 => /lib/libelf.so.1 (0xb36fe000)
        libbz2.so.1 => /lib/libbz2.so.1 (0xb36e6000)

**Comment by plfiorini** [comment]
The libkscreen error makes me think you have an older version.
Since 162b073d0aca855ff8db7405a7a12d364d95e871 the QPA platform plugin is passed by env var making libkscreen aware of where it takes screen info.
This resolved a similar error on Raspberry Pi 2.
Do you have this commit?

**Comment by plfiorini** [comment]
Also, you should run /usr/local/bin/hawaii-session -m hwcomposer instead of the compositor directly

**Comment by plfiorini** [comment]
If you want to test just the compositor (even if running the session manager is the way to bring the full desktop up) you need to:

export QT_QPA_PLATFORM=hwcomposer

and specify a plugin, for example the simple plugin from greenisland with:

/usr/local/bin/hawaii -p org.greenisland.simple

**Comment by fleixi** [comment]
im using the lates master (commit is in the log) and i have tested it with the hawaii-session --mode hwcomposer bevor.. the session manager is trying it 3 time with the same result.

i will try the compositor tomorrow.

**Comment by plfiorini** [comment]
Btw, this looks suspicious:

Physical size: QSizeF(0, 0)

According to this: http://doc.qt.io/qt-5/embedded-linux.html there are a couple of env vars to force a phisical size. Not sure whether a physical size of 0x0 is problematic but FYI the vars are QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT

**Comment by fleixi** [comment]
this shouldnt be a problem. with qt5.3 and the qml-compositor from the qtexamples and an hwcomposer plugin from aosp-android or mer-project wayland is running with the same output well.

only diffrent is that there is a comment that the wayland-plugin is loaded after the hwcomposer is started. but QSize is 0x0 too.

but i will take a look

**Comment by fleixi** [comment]
this is the output of the working hwcomposer with qt5.3
--------------------------
[odroid@localhost ~]$ EGLFS: Screen Info
 - Physical size: QSizeF(0, 0)
 - Screen size: QSize(1920, 1080)
 - Screen depth: 32
== hwcomposer module ==
 * Address: 0xb379a004
 * Module API Version: 1
 * HAL API Version: 100
 * Identifier: hwcomposer
 * Name: Samsung exynos5 hwcomposer module
 * Author: Samsung LSI
== hwcomposer module ==
== hwcomposer device ==
 * Version: 1010001 (interpreted as 1010001)
 * Module: 0xb379a004
== hwcomposer device ==
QEglScreen 0x2e6f0
 
"Qt Warning - invalid keysym: dead_actute"
EGL Wayland extension successfully initialized.
QEglWindow 0x4cab0: 0xbe8b73b4 0x0
 
WARNING: virtual int HWComposerNativeWindow::setBufferCount(int): allocated only 0 buffers out of 2
 
----------------------------
But on qt5.5 i couldnt compile this plugin anymore. (this is the used plugin https://github.com/mer-hybris/qt5-qpa-hwcomposer-plugin)

But greenisland and hawaii are build sucessfull.

this is the output of hahawaii-session:
----------------
hawaii.session.processcontroller: Compositor had an error: "Process crashed"
hawaii.session.processcontroller: Compositor retries left: 1
hawaii.session.processcontroller: Compositor finished with exit code 6
hawaii.session.processcontroller: Running: /usr/local/bin/hawaii -p org.hawaii.desktop
hawaii.session.manager: Autostart: "Spice vdagent" from "/etc/xdg/autostart/spice-vdagent.desktop"
hawaii.session.launcher: Launching "/usr/bin/spice-vdagent" from "/etc/xdg/autostart/spice-vdagent.desktop"
hawaii.session.launcher: Launched "/etc/xdg/autostart/spice-vdagent.desktop" (Spice vdagent) with pid 2733
hawaii.session.launcher: Application "Spice vdagent" finished with exit code 0
EGLFS: Screen Info
 - Physical size: QSizeF(0, 0)
 - Screen size: QSize(1920, 1080)
 - Screen depth: 32
== hwcomposer module ==
 * Address: 0xb2cf3004
 * Module API Version: 1
 * HAL API Version: 100
 * Identifier: hwcomposer
 * Name: Samsung exynos5 hwcomposer module
 * Author: Samsung LSI
== hwcomposer module ==
== hwcomposer device ==
 * Version: 1010001 (interpreted as 1010001)
 * Module: 0xb2cf3004
== hwcomposer device ==
QEglScreen 0x2ba58
 
Compositor ready, notify systemd on ""
kscreen: Launcher finished with exit code 2 , status 0
kscreen: Launcher failed to load any backend: KScreen will be useless
Screen configuration has an error: Failed to prepare backend
hawaii.session.processcontroller: Compositor had an error: "Process crashed"
Compositor won't start, aborting...
Aborted (core dumped)
[root@localhost qml-compositor]#
-----------------
i have tested to change the QSizeF but the compositor keeps crashing
if i only test the greenisland plugin i get the same output as i starting hawaii postet some post bevor

i think there are a problem with the compositor but there no useful errors.

**Comment by plfiorini** [comment]
Got a similar issue here with eglfs and Qt 5.5, looks like libkscreen is to blame.

**Comment by fleixi** [comment]
so at the moment the best to do is compiling everything on qt5.4 again? or have you some idea whats the problem in kscreen? or have you had an working version of qt5.5 and kscreen so i chould go some versions/commits back in kscreen?

**Comment by mihailescu2m** [comment]
I remember trying this with qt5.4, and had kscreen crashing as well, but I will try again and post my log, maybe it helps.

**Comment by plfiorini** [comment]
turns out the issue with eglfs and qt 5.5 was different, so nvm.
looks like the libkscreen backend manager runs the launcher eating all the debug output, so one way to debug this is to create a dbus session bus and manually run the backend launcher and see what does it say:

```sh
eval `dbus-launch --sh-syntax`
/usr/lib/kf5/kscreen_backend_launcher
```

**Comment by plfiorini** [comment]
I'm tempted to remove libkscreen and go straight to QScreen (provided that the API was improved compared to early versions). libkscreen used to be a nice library but recently the quality just dropped.

**Comment by mihailescu2m** [comment]
that might be much better, would also maybe remove some deps? can you please update if you are doing that, I want to test it

**Comment by plfiorini** [comment]
Removing libkscreen would make greenisland depend only on Qt stuff (except extra-cmake-modules for building but we can deal with it).
BTW hawaii-shell has less dependencies now: KService have been finally dropped in favor of libqtxdg and its xdg menu implementation so now the applications menu loads fast and the module requires less dependencies, yay!

I'll keep you posted

**Comment by fleixi** [comment]
thumps up. i looking forward to test hawaii too.

**Comment by plfiorini** [comment]
Update: libkscreen killing spree has started. Just finished the first commit (not yet pushed) that removes the dependency and replaces with a QScreen based backend. After a quick test with eglfs it seems fine, startup time is reduced and code is less complex (no need to map KScreen::Output to GreenIsland::Output). With the next patch I will add a fake backend to handle custom configurations, fake means that it doesn't take the configuration from a real backend such as QScreen but rather from a configuration file.

**Comment by plfiorini** [comment]
No more libkscreen as of https://github.com/greenisland/greenisland/commit/859a4a1dfc91abdff96d2744225a5563674bb110

**Comment by plfiorini** [comment]
Could you please try now?

**Comment by mihailescu2m** [comment]
root@jessie ~ # EGL_PLATFORM=hwcomposer hawaii -platform hwcomposer
EGLFS: Screen Info
 - Physical size: QSizeF(0, 0)
 - Screen size: QSize(1920, 1080)
 - Screen depth: 32
== hwcomposer module ==
 * Address: 0xb4ea3004
 * Module API Version: 1
 * HAL API Version: 100
 * Identifier: hwcomposer
 * Name: Samsung exynos5 hwcomposer module
 * Author: Samsung LSI
== hwcomposer module ==
== hwcomposer device ==
 * Version: 1010001 (interpreted as 1010001)
 * Module: 0xb4ea3004
== hwcomposer device ==
QEglScreen 0x3be00

greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject*)
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(QObject*)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject*)
greenisland.protocols.gtkshell: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.screenbackend.native: Screen added "" QRect(0,0 1920x1080)
QEglWindow 0xeec90: 0x56c40 0x0

WARNING: virtual int HWComposerNativeWindow::setBufferCount(int): allocated only 0 buffers out of 2
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
greenisland.compositor: Added primary output "" with geometry QRect(0,0 1920x1080)
greenisland.compositor: Showing window for output "" QRect(0,0 1920x1080)
greenisland.compositor: EGL version: 1.4 Android META-EGL
greenisland.compositor: EGL vendor: Android
greenisland.compositor: EGL client APIs: OpenGL_ES
greenisland.compositor: EGL extensions: EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image
	EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image
	EGL_KHR_fence_sync EGL_ANDROID_image_native_buffer EGL_HYBRIS_native_buffer
	EGL_HYBRIS_WL_hardware_buffer_handle EGL_WL_bind_wayland_display
	
greenisland.compositor: Loading scene on output "" QRect(0,0 1920x1080)
greenisland.compositor: Loading "org.hawaii.desktop" plugin for output "" QRect(0,0 1920x1080)
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed 
     import org.hawaii.misc 0.1 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed 
     import org.hawaii.session 0.1 as Session 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed 
     import Hawaii.Components 1.0 as Components 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed 
     import Hawaii.Themes 1.0 as Themes 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed 
     import GreenIsland 1.0 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed 
     import org.hawaii.misc 0.1 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed 
     import org.hawaii.session 0.1 as Session 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed 
     import Hawaii.Components 1.0 as Components 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed 
     import Hawaii.Themes 1.0 as Themes 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed 
     import GreenIsland 1.0 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed 
     import org.hawaii.misc 0.1 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed 
     import org.hawaii.session 0.1 as Session 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed 
     import Hawaii.Components 1.0 as Components 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed 
     import Hawaii.Themes 1.0 as Themes 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed 
     import GreenIsland 1.0 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed 
     import org.hawaii.misc 0.1 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed 
     import org.hawaii.session 0.1 as Session 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed 
     import Hawaii.Components 1.0 as Components 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed 
     import Hawaii.Themes 1.0 as Themes 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed 
     import GreenIsland 1.0 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed 
     import org.hawaii.misc 0.1 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed 
     import org.hawaii.session 0.1 as Session 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed 
     import Hawaii.Components 1.0 as Components 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed 
     import Hawaii.Themes 1.0 as Themes 
     ^
file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed 
     import GreenIsland 1.0 
     ^
greenisland.compositor: One or more errors have occurred loading the plugin:
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:32:1: module "org.hawaii.misc" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:33:1: module "org.hawaii.session" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:30:1: module "Hawaii.Components" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:31:1: module "Hawaii.Themes" is not installed"
greenisland.compositor: * "file:///usr/local/share/greenisland/org.hawaii.desktop/Compositor.qml:29:1: module "GreenIsland" is not installed"
greenisland.compositor: Scene load time: 62 ms

**Comment by fleixi** [comment]
same here but i get a segmentation error.

-------

root@localhost:/home/odroid[root@localhost odroid]# EGL_PLATFORM=hwcomposer /usr/local/bin/hawaii -platform hwcomposer
EGLFS: Screen Info
 - Physical size: QSizeF(0, 0)
 - Screen size: QSize(1920, 1080)
 - Screen depth: 32
== hwcomposer module ==
 * Address: 0xb2cb3004
 * Module API Version: 1
 * HAL API Version: 100
 * Identifier: hwcomposer
 * Name: Samsung exynos5 hwcomposer module
 * Author: Samsung LSI
== hwcomposer module ==
== hwcomposer device ==
 * Version: 1010001 (interpreted as 1010001)
 * Module: 0xb2cb3004
== hwcomposer device ==
QEglScreen 0x2c9d0
 
greenisland.protocols.wlshell.trace: GreenIsland::WlShellGlobal::WlShellGlobal(QObject*)
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.wlshell.trace: virtual const wl_interface* GreenIsland::WlShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: GreenIsland::XdgShellGlobal::XdgShellGlobal(QObject*)
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.xdgshell.trace: virtual const wl_interface* GreenIsland::XdgShellGlobal::interface() const
greenisland.protocols.gtkshell: GreenIsland::GtkShellGlobal::GtkShellGlobal(QObject*)
greenisland.protocols.gtkshell: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.protocols.gtkshell: virtual const wl_interface* GreenIsland::GtkShellGlobal::interface() const
greenisland.screenbackend.native: Screen added "" QRect(0,0 1920x1080)
QEglWindow 0xae868: 0x46bf8 0x0
 
WARNING: virtual int HWComposerNativeWindow::setBufferCount(int): allocated only 0 buffers out of 2
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
greenisland.compositor: Added primary output "" with geometry QRect(0,0 1920x1080)
greenisland.compositor: Showing window for output "" QRect(0,0 1920x1080)
Segmentation fault (core dumped)

-----

**Comment by plfiorini** [comment]
@mihailescu2m import errors fixed on IRC, it was a path issue.
Note that hawaii-session sets all the env vars if it was installed with a prefix != /usr otherwise one has to set QML2_IMPORT_PATH and probably more such as QT_PLUGIN_PATH.

There are some QPainter and font errors on XU though, but those problems seem to be related to Qt.
Here's the relevant paste: http://pastebin.com/R64449b8

As for @fleixi crash I have a suspicion since it happens right before the window is shown: EGL
Maybe it links to the wrong EGL library (from Mesa?). I had to do something different for the RaspberryPi (check the cmake module https://github.com/hawaii-desktop/hawaii-shell/blob/master/cmake/FindBcmHost.cmake).

What EGL library does this board use @fleixi ?
Maybe you can check to what EGL is Qt linked to.

**Comment by plfiorini** [comment]
Looks like libhybris has its EGL: https://github.com/libhybris/libhybris/tree/master/hybris/egl

**Comment by fleixi** [comment]
Thanks i know, maybe i have forgotten to export the pkgconfig path as im compilied it the last time. Normaly i always use the egl from libhybris. I will recompile and test it again tomorrow.

**Comment by plfiorini** [comment]
@fleixi Or Green Island and Hawaii pick up the wrong one, maybe in this case I can do something.
However it seems that libhybris has a pkg-config file which means that in theory it should pickup the correct one.

**Comment by fleixi** [comment]
Ok thats something i will get fixed. I will post my summery tomorrow

**Comment by plfiorini** [comment]
Thanks!

**Comment by plfiorini** [comment]
Closing, apparently the crash is fixed.
