### ISSUE TITLE
I think commit 7d98212eeca65200e189c8db1c1408802012f819 broke the build

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#179]
I get this output:

-- Performing Test _OFFT_IS_64BIT - Failed
CMake Error at CMakeLists.txt:39 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

-- Found KF5Config: /opt/lib/i386-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.8.0") 
-- Found KF5CoreAddons: /opt/lib/i386-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.8.0") 
-- Found KF5Solid: /opt/lib/i386-linux-gnu/cmake/KF5Solid/KF5SolidConfig.cmake (found version "5.8.0") 
-- Found KF5: success (found suitable version "5.8.0", minimum required is "5.1.0") found components:  Config CoreAddons Solid 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Found EGL: /opt/lib/i386-linux-gnu/libEGL.so (found version "1.4") 
-- Found Wayland_Client: /opt/lib/i386-linux-gnu/libwayland-client.so (found version "1.7.90") 
-- Found Wayland_Server: /opt/lib/i386-linux-gnu/libwayland-server.so (found version "1.7.90") 
-- Found Wayland_Cursor: /opt/lib/i386-linux-gnu/libwayland-cursor.so (found version "1.7.90") 
-- Found Wayland_Egl: /opt/lib/i386-linux-gnu/libwayland-egl.so (found version "10.3.7") 
-- Found Wayland: /opt/lib/i386-linux-gnu/libwayland-client.so;/opt/lib/i386-linux-gnu/libwayland-server.so;/opt/lib/i386-linux-gnu/libwayland-cursor.so;/opt/lib/i386-linux-gnu/libwayland-egl.so (found suitable version "1.7.90", minimum required is "1.2.0")  
-- Found Wayland: /opt/lib/i386-linux-gnu/libwayland-client.so;/opt/lib/i386-linux-gnu/libwayland-server.so;/opt/lib/i386-linux-gnu/libwayland-cursor.so;/opt/lib/i386-linux-gnu/libwayland-egl.so (found suitable version "1.7.90", minimum required is "1.2.0") found components:  Client 
-- Found QtWaylandScanner: /opt/bin/qtwaylandscanner  
CMake Error at data/systemd/CMakeLists.txt:27 (install):
  install FILES given no DESTINATION!

**Comment by plfiorini** [comment]
Should be fixed now.

**Comment by n3rdopolis** [comment]
It works! Thanks.

**Comment by plfiorini** [comment]
Thanks for reporting :)
