### ISSUE TITLE
Compillingerror: Missing stropts.h Fedora21

### ISSUE THREAD

**Issue by fleixi** [hawaii-desktop/hawaii-shell#182]
Fedora doesnt have stropts.h so compilling crashing with this error:

---------------------------------------------------------------------
[ 93%] [ 94%] Building CXX object session/CMakeFiles/hawaii-session.dir/loginmanager/loginmanagerbackend.cpp.o
Building CXX object session/CMakeFiles/hawaii-session.dir/loginmanager/logindbackend.cpp.o
[ 95%] Building CXX o[ 93%] [ 94%] Building CXX object session/CMakeFiles/hawaii-session.dir/loginmanager/loginmanagerbackend.cpp.o
Building CXX object session/CMakeFiles/hawaii-session.dir/loginmanager/logindbackend.cpp.o
[ 95%] Building CXX object session/CMakeFiles/hawaii-session.dir/loginmanager/fakebackend.cpp.o
[ 96%] Building CXX object session/CMakeFiles/hawaii-session.dir/powermanager/powermanager.cpp.o
/media/usb-platte/home/odroid/git/hawaii/hawaii-shell/session/vthandler.cpp:30:21: Error: stropts.h: File not found
 #include <stropts.h>
                     ^
Kompilierung beendet.
[ 96%] Built target hawaii
[ 96%] Building CXX object session/CMakeFiles/hawaii-session.dir/powermanager/powermanagerbackend.cpp.o
session/CMakeFiles/hawaii-session.dir/build.make:273: recipe for target 'session/CMakeFiles/hawaii-session.dir/vthandler.cpp.o' failed
make[2]: *** [session/CMakeFiles/hawaii-session.dir/vthandler.cpp.o] Error 1
make[2]: *** Warte auf noch nicht beendete Prozesse...
CMakeFiles/Makefile2:1625: recipe for target 'session/CMakeFiles/hawaii-session.dir/all' failed
make[1]: *** [session/CMakeFiles/hawaii-session.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2bject session/CMakeFiles/hawaii-session.dir/loginmanager/fakebackend.cpp.o
[ 96%] Building CXX object session/CMakeFiles/hawaii-session.dir/powermanager/powermanager.cpp.o
/media/usb-platte/home/odroid/git/hawaii/hawaii-shell/session/vthandler.cpp:30:21: schwerwiegender Fehler: stropts.h: Datei oder Verzeichnis nicht gefunden
 #include <stropts.h>
                     ^
Kompilierung beendet.
[ 96%] Built target hawaii
[ 96%] Building CXX object session/CMakeFiles/hawaii-session.dir/powermanager/powermanagerbackend.cpp.o
session/CMakeFiles/hawaii-session.dir/build.make:273: recipe for target 'session/CMakeFiles/hawaii-session.dir/vthandler.cpp.o' failed
make[2]: *** [session/CMakeFiles/hawaii-session.dir/vthandler.cpp.o] Error 1
make[2]: *** Warte auf noch nicht beendete Prozesse...
CMakeFiles/Makefile2:1625: recipe for target 'session/CMakeFiles/hawaii-session.dir/all' failed
make[1]: *** [session/CMakeFiles/hawaii-session.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2

----------------------------

Sorry for the german output, have no posibility to change it at the moment. But it says stropts.h is missing and this is not part of Fedora or any Package from Fedora

i have replaed it with #include <sys/ioctl.h> and everything is compiling. but i havent test it if it is working.

**Comment by plfiorini** [comment]
Likely fixed by 2b798a6 please confirm.

**Comment by fleixi** [comment]
Is working again. Thx
