### ISSUE TITLE
Request for calling Hawaii under an existing WAYLAND_DISPLAY supporting fullscreen-shell

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#185]
Hi.

I would like to request the ability to be able to call a Hawaii session under an existing Wayland session enabled with fullscreen-shell

The benefit to this that my Wayland Login Manager calls up this server before calling the server, and it detects if it should start the host Weston with the DRM backend, or the fbdev backend

I attempted and now it seems to try to use the existing WAYLAND_DISPLAY for the new server:
(calling hawaii-session -m wayland with the below patch )

diff --git a/session/compositorlauncher.cpp b/session/compositorlauncher.cpp
index 3e5197d..7e2bab2 100644
--- a/session/compositorlauncher.cpp
+++ b/session/compositorlauncher.cpp
@@ -283,6 +283,9 @@ QStringList CompositorLauncher::compositorArgs() const
     case NestedMode:
         args << QStringLiteral("--socket=%1").arg(m_compositor->socketName());
         break;
+    case WaylandMode:
+        args << QStringLiteral("--socket=%1").arg(m_compositor->socketName());
+        break;
     default:
         break;
     }
diff --git a/session/main.cpp b/session/main.cpp
index dbdcc79..489bcc1 100644
--- a/session/main.cpp
+++ b/session/main.cpp
@@ -134,6 +134,8 @@ int main(int argc, char *argv[])
         launcher->setMode(CompositorLauncher::HwComposerMode);
     else if (mode == QStringLiteral("nested"))
         launcher->setMode(CompositorLauncher::NestedMode);
+    else if (mode == QStringLiteral("wayland"))
+        launcher->setMode(CompositorLauncher::WaylandMode);
     else if (!mode.isEmpty()) {
         qWarning() << "Invalid mode argument" << mode;
         return 1;
diff --git a/session/processcontroller.h b/session/processcontroller.h
index 46be07a..89a164b 100644
--- a/session/processcontroller.h
+++ b/session/processcontroller.h
@@ -43,7 +43,8 @@ public:
     enum Mode {
         EglFSMode = 0,
         HwComposerMode,
-        NestedMode
+        NestedMode,
+        WaylandMode
     };
 
     ProcessController(const QString &mode, QObject *parent = Q_NULLPTR);

**Comment by n3rdopolis** [comment]
Actually weirdly enough greenisland-launcher is doing the same thing, 
 unable to lock lockfile $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY

and I didn't do anything to change greenisland

**Comment by n3rdopolis** [comment]
Hi
I forgot to mention my QT_QPA_PLATFORM is wayland when I tried

Thanks

**Comment by n3rdopolis** [comment]
Hi.

Any update on this? I think I should file a bug on greenisland because it seems I can't run greenisland itself under QT_QPA_PLATFORM=wayland as well... 
Fake screen config is not allowed when Green Island is nested...

**Comment by plfiorini** [comment]
Should be fixed now.

**Comment by plfiorini** [comment]
Please reopen if there's still problems.

**Comment by n3rdopolis** [comment]
Cool. It seems that I can call hawaii, and it will work,
however it seems that hawaii-session doesn't work, or allow a socket to be passed through to Hawaii. I'm OK with calling hawaii directly, unless there is something I am missing by calling hawaii directly

**Comment by n3rdopolis** [comment]
I just realised hawaii-session is a script, so never mind. I thought hawaii needed it for dbus or something, but I guess not anymore

**Comment by plfiorini** [comment]
Yep it's a script now, for some reason I had issues respawning the binary with dbus-launch from itself.
