### ISSUE TITLE
Hawaii doesn't run nested under Wayland when DISPLAY is set

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#188]
It seems that when hawaii-session detects that the DISPLAY variable is set, which is usually set for XWayland, that it appends the fake screen data. Greenisland when QT_QPA_PLATFORM=wayland exits when fake screen data is passed.

Workaround is to unset DISPLAY

**Comment by plfiorini** [comment]
Should be fixed now

**Comment by plfiorini** [comment]
Please reopen if there's still problems.
