### ISSUE TITLE
Invalid screen physical size on virtual machines

### ISSUE THREAD

**Issue by plfiorini** [hawaii-desktop/hawaii-shell#204]
For some reason the panel is not loaded and the clock doesn't respond to clicks.
It works with real hardware (tested with Intel GPU on laptop and NUC and months ago with an old GeForce 8800 GT) but on virtual machines with QXL or VMWare GPU it has this problem.
Keyboard works: in fact Super+L locks the screen and Ctrl+Alt+Backspaces opens the logout screen.

Screenshot: https://imgur.com/oG0ureq

**Comment by mastaiza** [comment]
I have the same error. Intel

**Comment by plfiorini** [comment]
Investigation shows that it might be a problem that depends on fonts.
Device independent units are implemented based on font size, looks like on some setups it doesn't get that information and returns wrong values.

**Comment by plfiorini** [comment]
Now that Qt HiDpi support is better I might invest some time in rewriting the Units module using better device independent information.

**Comment by plfiorini** [comment]
Size issue figured out: http://imgur.com/TsnikZo

There are other issues on VM (not sure they happen on your setup too) that I can't experience on my real computers like:

- Infinity DPI
- No mouse input (actually I think that coordinates are screwed, might be related to the previous point because of DPI adjustments)
- Meta+Space doesn't open the Menu although all other shortcuts work

**Comment by plfiorini** [comment]
This is definitely a driver issue. When the connector reports an empty physical size (0x0 mm or -1x-1 mm) everything stops working.

With https://github.com/greenisland/greenisland/issues/180 the offending physical size will be changed to the one of a 22" monitor.

**Comment by plfiorini** [comment]
Improvements: http://imgur.com/XDL1Fuc

pixel density still wrong.

**Comment by plfiorini** [comment]
Fixed pixel density.

All is ok except for mouse input. In this case it seems that mouse pressed and released events are sent by libinput but not the pointer coordinates.

**Comment by plfiorini** [comment]
Mouse is a seprate issue: https://github.com/greenisland/greenisland/issues/181
