### ISSUE TITLE
crash in GreenIsland

### ISSUE THREAD

**Issue by kdt3rd** [hawaii-desktop/hawaii-shell#205]
I am experimenting with a master branch git build of hawaii under arch linux by pulling the AUR PKGBUILDs, and am seeing a crash as soon as I try to do just about anything that involves windows opening or changing, in GreenIsland::WlCursorTheme::changeCursor. It could be that I don't have something fully installed (or some dependency I didn't know about), but weston seems to run fine, and hawaii-terminal seems to run inside weston, so it seems like it is some mismatch in greenisland and wayland. I tried with both the default wayland install as well as the latest git beta.

When I run hawaii-session inside weston (--mode=nested) it doesn't fail with in setCursor, but rather seems to crash very often in the focus handler.

Below is a stack trace for the above set cursor issue mentioned, I don't yet know where to look next to debug further, any suggestions are appreciated:

#0  0x00007fe9bbfeb5f8 in raise () from /usr/lib/libc.so.6
#1  0x00007fe9bbfeca7a in abort () from /usr/lib/libc.so.6
#2  0x00007fe9bbdb2d8f in ?? ()
#3  0x00007fe9bbdaf045 in wl_proxy_marshal_array_constructor_versioned () from /usr/lib/libwayland-client.so.0
#4  0x00007fe9bbdaf18c in wl_proxy_marshal () from /usr/lib/libwayland-client.so.0
#5  0x00007fe9be2e4ada in GreenIsland::WlCursorTheme::changeCursor (this=0x3f7f560, 
    shape=shape@entry=GreenIsland::WlCursorTheme::ArrowCursor)
    at /tmp/AUR/greenisland-git/src/greenisland/src/server/client/wlcursortheme.cpp:298
#6  0x00007fe9be2d4087 in GreenIsland::Compositor::resetMouseCursor (this=<optimized out>)
    at /tmp/AUR/greenisland-git/src/greenisland/src/server/compositor.cpp:380
#7  0x00007fe9be2d4a8d in GreenIsland::Compositor::qt_static_metacall (
    _o=_o@entry=0x7fe9be548a80 <GreenIsland::(anonymous namespace)::Q_QGS_s_compositor::innerFunction()::holder>, 
    _c=_c@entry=QMetaObject::InvokeMetaMethod, _id=_id@entry=32, _a=_a@entry=0x7ffe3ff55230)
    at /tmp/AUR/greenisland-git/src/build/src/server/moc_compositor.cpp:280
#8  0x00007fe9be2d5438 in GreenIsland::Compositor::qt_metacall (
    this=0x7fe9be548a80 <GreenIsland::(anonymous namespace)::Q_QGS_s_compositor::innerFunction()::holder>, 
    _c=QMetaObject::InvokeMetaMethod, _id=32, _a=0x7ffe3ff55230)
    at /tmp/AUR/greenisland-git/src/build/src/server/moc_compositor.cpp:522
#9  0x00007fe9bda24f69 in ?? () from /usr/lib/libQt5Qml.so.5
#10 0x00007fe9bd9a394e in ?? () from /usr/lib/libQt5Qml.so.5
#11 0x00007fe9bd9a4805 in ?? () from /usr/lib/libQt5Qml.so.5
#12 0x00007fe9bd9a50cd in QV4::QObjectMethod::callInternal(QV4::CallData*) () from /usr/lib/libQt5Qml.so.5
#13 0x00007fe9bd9bbaa3 in QV4::Runtime::callProperty(QV4::ExecutionEngine*, int, QV4::CallData*) ()
   from /usr/lib/libQt5Qml.so.5
#14 0x00007fe99c0d0d81 in ?? ()
#15 0x0000000002765db0 in ?? ()
#16 0x00000003ae43fe00 in ?? ()
#17 0x00007ffe3ff558c0 in ?? ()
#18 0x0000000002934aa0 in ?? ()
#19 0x00007fe99f000108 in ?? ()
#20 0x00000000028feb28 in ?? ()
#21 0x00007fe99f000058 in ?? ()
#22 0x00007fe99f000060 in ?? ()
#23 0x0000000002765db0 in ?? ()
#24 0x00007fe9bd95c10a in ?? () from /usr/lib/libQt5Qml.so.5
#25 0x00007fe9bda4c35f in ?? () from /usr/lib/libQt5Qml.so.5
#26 0x00007fe9bd9f26f6 in QQmlBoundSignalExpression::evaluate(void**) () from /usr/lib/libQt5Qml.so.5
#27 0x00007fe9bd9f2fab in ?? () from /usr/lib/libQt5Qml.so.5
#28 0x00007fe9bda2f7ee in QQmlNotifier::emitNotify(QQmlNotifierEndpoint*, void**) () from /usr/lib/libQt5Qml.so.5
#29 0x00007fe9bd9d224c in QQmlData::signalEmitted(QAbstractDeclarativeData*, QObject*, int, void**) ()
   from /usr/lib/libQt5Qml.so.5
#30 0x00007fe9bc992c20 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#31 0x00007fe9bb5f21d2 in QQuickMouseArea::positionChanged(QQuickMouseEvent*) () from /usr/lib/libQt5Quick.so.5
#32 0x00007fe9bb52cea9 in QQuickMouseArea::hoverMoveEvent(QHoverEvent*) () from /usr/lib/libQt5Quick.so.5
#33 0x00007fe9bb4b14c8 in QQuickItem::event(QEvent*) () from /usr/lib/libQt5Quick.so.5
#34 0x00007fe9bd2579ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#35 0x00007fe9bd25ce86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#36 0x00007fe9bc964bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#37 0x00007fe9bb4c065c in QQuickWindow::sendEvent(QQuickItem*, QEvent*) () from /usr/lib/libQt5Quick.so.5
#38 0x00007fe9bb4c2d52 in QQuickWindowPrivate::sendHoverEvent(QEvent::Type, QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool) () from /usr/lib/libQt5Quick.so.5
#39 0x00007fe9bb4c36cf in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#40 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#41 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#42 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#43 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#44 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#45 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#46 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#47 0x00007fe9bb4c31ae in QQuickWindowPrivate::deliverHoverEvent(QQuickItem*, QPointF const&, QPointF const&, QFlags<Qt::KeyboardModifier>, bool&) () from /usr/lib/libQt5Quick.so.5
#48 0x00007fe9bb4c6f50 in QQuickWindow::mouseMoveEvent(QMouseEvent*) () from /usr/lib/libQt5Quick.so.5
#49 0x00007fe9be2e1981 in GreenIsland::OutputWindow::mouseMoveEvent (this=0x281c940, event=0x7ffe3ff58760)
    at /tmp/AUR/greenisland-git/src/greenisland/src/server/outputwindow.cpp:230
#50 0x00007fe9bccae455 in QWindow::event(QEvent*) () from /usr/lib/libQt5Gui.so.5
#51 0x00007fe9bb4c8081 in QQuickWindow::event(QEvent*) () from /usr/lib/libQt5Quick.so.5
#52 0x00007fe9bd2579ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#53 0x00007fe9bd25ce86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#54 0x00007fe9bc964bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#55 0x00007fe9bcca55f1 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt5Gui.so.5
#56 0x00007fe9bcca72b5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#57 0x00007fe9bcc8c6d8 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Gui.so.5
#58 0x00007fe9b1dac890 in userEventSourceDispatch(_GSource*, int (*)(void*), void*) ()
   from /usr/lib/libGreenIslandPlatform.so.0
#59 0x00007fe9ba10cdc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#60 0x00007fe9ba10d020 in ?? () from /usr/lib/libglib-2.0.so.0
#61 0x00007fe9ba10d0cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#62 0x00007fe9bc9bb54f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#63 0x00007fe9bc96257a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#64 0x00007fe9bc96a53c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#65 0x0000000000408114 in main (argc=3, argv=<optimized out>)
    at /tmp/AUR/hawaii-shell-git/src/hawaii-shell/compositor/main.cpp:142

**Comment by plfiorini** [comment]
Should be fixed now.
Please reopen if it happens again.
